### ISSUE TITLE
Failed tests, category 1, caused by error handle. 

### ISSUE THREAD

**Issue by EmisonLu** [second-state/substrate-wasmedge#2]
As mentioned in [issue#1](https://github.com/second-state/substrate-wasmedge/issues/1), the failed test cases can be divided into three categories, the first of which contains the following three cases.

```bash
failures:
    integration_tests::call_not_existing_function_compiled_wasmedge
    integration_tests::call_yet_another_not_existing_function_compiled_wasmedge
    integration_tests::panic_in_spawned_instance_panics_on_joining_its_result_compiled_wasmedge
```

The current version of WasmEdge only supports the pre-defined error code for runtime, but the user-defined error codes used in host functions are not supported, which is the cause of the failure of the above tests. WasmEdge 0.11.0 is planning to fix this issue. More details can be found in [issue#1715](https://github.com/WasmEdge/WasmEdge/issues/1715).

**Comment by juntao** [comment]
WasmEdge 0.11 has now been released. Has this test case passed?

**Comment by EmisonLu** [comment]
Thanks for the reminder! I'll have a look at it soon!

**Comment by EmisonLu** [comment]
It has been fixed in this [commit](https://github.com/second-state/substrate-wasmedge/commit/ca20152fd95d7962ee5717e2bc2fe6e29bc4a47a).
